openapi: 3.2.0
info:
  version: 1.2.3(1S)
  title: Jobox Ai External API
servers:
- url: https://https://staging.jobox.ai/Kili
tags:
- name: External
paths:
  /external:
    post:
      tags:
      - External
      operationId: create_5
      responses:
        default:
          description: successful operation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExternalPayment'
      summary: Create 5
      x-summary-source: derived
    put:
      tags:
      - External
      operationId: update_2
      responses:
        default:
          description: successful operation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExternalPayment'
      summary: Update 2
      x-summary-source: derived
    delete:
      tags:
      - External
      operationId: delete
      responses:
        default:
          description: successful operation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExternalPayment'
      summary: Delete
      x-summary-source: derived
components:
  schemas:
    ExternalPayment:
      type: object
      properties:
        id:
          type: integer
          format: int64
        jobId:
          type: integer
          format: int64
        externalId:
          type: integer
          format: int64
        userId:
          type: integer
          format: int64
        percent:
          type: number
        createdAt:
          type: string
          format: date-time
