openapi: 3.2.0
info:
  version: 1.2.3(1S)
  title: Jobox Ai Identification API
servers:
- url: https://https://staging.jobox.ai/Kili
tags:
- name: Identification
paths:
  /identification/{user_id}:
    get:
      tags:
      - Identification
      operationId: read_12
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: user-id
        in: header
        required: false
        schema:
          type: integer
          format: int64
      responses:
        default:
          description: successful operation
      summary: Read 12
      x-summary-source: derived
