openapi: 3.2.0
info:
  version: 1.2.3(1S)
  title: Jobox Ai Bankinfo API
servers:
- url: https://https://staging.jobox.ai/Kili
tags:
- name: bankinfo
paths:
  /bankinfo/users/{user_id}:
    get:
      tags:
      - bankinfo
      operationId: readByUserId
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: User-Id
        in: header
        required: false
        schema:
          type: integer
          format: int64
      responses:
        default:
          description: successful operation
  /bankinfo:
    post:
      tags:
      - bankinfo
      operationId: create_1
      parameters:
      - name: User-Id
        in: header
        required: false
        schema:
          type: integer
          format: int64
      - name: version
        in: header
        required: false
        schema:
          type: string
      responses:
        default:
          description: successful operation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BankInfo'
    put:
      tags:
      - bankinfo
      operationId: update
      responses:
        default:
          description: successful operation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BankInfo'
    delete:
      tags:
      - bankinfo
      operationId: archive
      responses:
        default:
          description: successful operation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BankInfo'
  /bankinfo/{bank_id}:
    get:
      tags:
      - bankinfo
      operationId: read
      parameters:
      - name: bank_id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: User-Id
        in: header
        required: false
        schema:
          type: integer
          format: int64
      responses:
        default:
          description: successful operation
components:
  schemas:
    BankInfo:
      type: object
      properties:
        id:
          type: integer
          format: int64
        addedByUserId:
          type: integer
          format: int64
        forUserId:
          type: integer
          format: int64
        accountName:
          type: string
        bankName:
          type: string
        routingNumber:
          type: string
        accountNumber:
          type: string
        active:
          type: boolean
        createdAt:
          type: string
          format: date-time
