openapi: 3.2.0
info:
  version: 1.2.3(1S)
  title: Jobox Ai Disputes API
servers:
- url: https://https://staging.jobox.ai/Kili
tags:
- name: Disputes
paths:
  /disputes/{dispute_id}:
    get:
      tags:
      - Disputes
      operationId: read_4
      parameters:
      - name: User-Id
        in: header
        required: false
        schema:
          type: integer
          format: int64
      - name: dispute_id
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: successful operation
      summary: Read 4
      x-summary-source: derived
  /disputes/users/{user_id}:
    get:
      tags:
      - Disputes
      operationId: list
      parameters:
      - name: User-Id
        in: header
        required: false
        schema:
          type: integer
          format: int64
      - name: user_id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: range
        in: query
        required: false
        schema:
          type: integer
          format: int32
      - name: page_num
        in: query
        required: false
        schema:
          type: integer
          format: int32
      responses:
        default:
          description: successful operation
      summary: List
      x-summary-source: derived
