openapi: 3.2.0
info:
  version: 1.2.3(1S)
  title: Jobox Ai Status API
servers:
- url: https://https://staging.jobox.ai/Kili
tags:
- name: Status
paths:
  /:
    get:
      tags:
      - Status
      operationId: read_15
      responses:
        default:
          description: successful operation
      summary: Read 15
      x-summary-source: derived
