openapi: 3.2.0
info:
  version: 1.2.3(1S)
  title: Jobox Ai Paymentlog API
servers:
- url: https://https://staging.jobox.ai/Kili
tags:
- name: paymentlog
paths:
  /paymentlog/{id}:
    get:
      tags:
      - paymentlog
      operationId: read_11
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        default:
          description: successful operation
      summary: Read 11
      x-summary-source: derived
  /paymentlog:
    post:
      tags:
      - paymentlog
      operationId: create_11
      parameters:
      - name: User-Id
        in: header
        required: false
        schema:
          type: integer
          format: int64
      - name: for_tech
        in: query
        required: false
        schema:
          type: boolean
      responses:
        default:
          description: successful operation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentLogDTO'
      summary: Create 11
      x-summary-source: derived
    delete:
      tags:
      - paymentlog
      operationId: delete_1
      responses:
        default:
          description: successful operation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentLog'
      summary: Delete 1
      x-summary-source: derived
  /paymentlog/list:
    post:
      tags:
      - paymentlog
      operationId: create_12
      parameters:
      - name: User-Id
        in: header
        required: false
        schema:
          type: integer
          format: int64
      - name: for_tech
        in: query
        required: false
        schema:
          type: boolean
      responses:
        default:
          description: successful operation
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/PaymentLogDTO'
      summary: Create 12
      x-summary-source: derived
components:
  schemas:
    PaymentLogDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        paymentId:
          type: integer
          format: int64
        jobId:
          type: integer
          format: int64
        amount:
          type: number
        tip:
          type: number
        notes:
          type: string
        paymentType:
          type: string
          enum:
          - CARD
          - CASH
          - EXTERNAL
          - CHECK
        transactionType:
          type: string
          enum:
          - PAYMENT
          - REFUND
          - DISPUTE
        userId:
          type: integer
          format: int64
        createdAt:
          type: string
          format: date-time
        cardPaymentDetails:
          $ref: '#/components/schemas/CardPaymentDetails'
    PaymentLog:
      type: object
      properties:
        id:
          type: integer
          format: int64
        paymentId:
          type: integer
          format: int64
        jobId:
          type: integer
          format: int64
        amount:
          type: number
        tip:
          type: number
        notes:
          type: string
        paymentType:
          type: string
          enum:
          - CARD
          - CASH
          - EXTERNAL
          - CHECK
        transactionType:
          type: string
          enum:
          - PAYMENT
          - REFUND
          - DISPUTE
        userId:
          type: integer
          format: int64
        createdAt:
          type: string
          format: date-time
    CardPaymentDetails:
      type: object
      properties:
        id:
          type: integer
          format: int64
        paymentLogId:
          type: integer
          format: int64
        userId:
          type: integer
          format: int64
        transactionPercent:
          type: number
        interchangeFee:
          type: number
        ccTotalFee:
          type: number
        paymentSource:
          type: string
          enum:
          - STRIPE
        paymentSourceId:
          type: string
        brand:
          type: string
        customer:
          type: string
        funding:
          type: string
        cardEntryMethod:
          type: string
          enum:
          - SWIPE
          - CHIP
          - MANUAL
        fingerprint:
          type: string
        last4:
          type: string
        zip:
          type: string
        createdAt:
          type: string
          format: date-time
        active:
          type: boolean
